name: Tests

on:
  push:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: street-cred Tests and Coverage
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.87.0
      - name: Generate code coverage
        run: |
          cargo tarpaulin --engine llvm
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ github.token }}
